description = "Backups files to a b2 bucket"

[global]
ignore = [
    ".venv",
    "__pycache__",
    "*.pyc",
    ".flatpak-builder",
    "node_modules",
    ".stack-work",
    "lost+found"
]
dry_run = true
progress = true

[backups]
    [backups.remote]
    src = "/mnt/user/Backups"
    dst = "b2:bucket_name_here"

